version = 0.1
[default.deploy.parameters]
stack_name = "arthromate"
resolve_s3 = true
s3_prefix = "arthromate"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
